export const countryTypes = { 

    FETCH_BY_COUNTRY_START:`FETCH_BY_COUNTRY_START`,
    FETCH_BY_COUNTRY_SUCCESS:`FETCH_BY_COUNTRY_SUCCESS`,
    FETCH_BY_COUNTRY_FAILURE:`FETCH_BY_COUNTRY_FAILURE`
    
}